-- indomie.sql — every product whose title starts with INDOMIE, with the fields C1 compares across would-be siblings.
WITH
p AS (SELECT * EXCEPT(rn) FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY id ORDER BY datastream_metadata.source_timestamp DESC, datastream_metadata.change_sequence_number DESC) rn FROM `solvent-staging.production_append_public.catalogue_product` WHERE datastream_metadata.source_timestamp <= UNIX_MILLIS(TIMESTAMP '2026-09-19 10:27:00+00')) WHERE rn=1 AND datastream_metadata.change_type != 'DELETE'),
pi AS (SELECT * EXCEPT(rn) FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY id ORDER BY datastream_metadata.source_timestamp DESC, datastream_metadata.change_sequence_number DESC) rn FROM `solvent-staging.production_append_public.catalogue_productimage` WHERE datastream_metadata.source_timestamp <= UNIX_MILLIS(TIMESTAMP '2026-09-19 10:27:00+00')) WHERE rn=1 AND datastream_metadata.change_type != 'DELETE'),
pav AS (SELECT * EXCEPT(rn) FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY id ORDER BY datastream_metadata.source_timestamp DESC, datastream_metadata.change_sequence_number DESC) rn FROM `solvent-staging.production_append_public.catalogue_productattributevalue` WHERE datastream_metadata.source_timestamp <= UNIX_MILLIS(TIMESTAMP '2026-09-19 10:27:00+00')) WHERE rn=1 AND datastream_metadata.change_type != 'DELETE'),
pa AS (SELECT * EXCEPT(rn) FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY id ORDER BY datastream_metadata.source_timestamp DESC, datastream_metadata.change_sequence_number DESC) rn FROM `solvent-staging.production_append_public.catalogue_productattribute` WHERE datastream_metadata.source_timestamp <= UNIX_MILLIS(TIMESTAMP '2026-09-19 10:27:00+00')) WHERE rn=1 AND datastream_metadata.change_type != 'DELETE'),
ind AS (SELECT * FROM p WHERE REGEXP_CONTAINS(UPPER(title), r'^INDOMIE')),
img AS (SELECT product_id, COUNT(*) AS images FROM pi WHERE product_id IN (SELECT id FROM ind) GROUP BY 1),
att AS (SELECT pav.product_id, STRING_AGG(CONCAT(pa.code,'=',COALESCE(pav.value_text, CAST(pav.value_float AS STRING))), '; ' ORDER BY pa.code) AS attrs FROM pav JOIN pa ON pa.id=pav.attribute_id WHERE pav.product_id IN (SELECT id FROM ind) GROUP BY 1)
SELECT ind.id, ind.upc, ind.title, ind.title_staff, ind.is_active, ind.is_public, ind.is_offline_only, ind.main_category_id, ind.product_class_id, LENGTH(COALESCE(ind.description,'')) AS description_len, ind.thumbnail_url_cache IS NOT NULL AS has_thumb, COALESCE(img.images,0) AS images, att.attrs
FROM ind LEFT JOIN img ON img.product_id=ind.id LEFT JOIN att ON att.product_id=ind.id
ORDER BY ind.is_active DESC, ind.title;
